{% set version = "1.5.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-celestial
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/celestial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/celestial/celestial_{{ version }}.tar.gz
  sha256: 2c6fc002e0313658a970873461846e11bdc205038e120b4b27f305ca2996d2f4

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-nistunits
    - r-rann
    - r-rcpp
    - r-pracma
  run:
    - r-base
    - r-nistunits
    - r-rann
    - r-rcpp
    - r-pracma

test:
  commands:
    - $R -e "library('celestial')"           # [not win]
    - "\"%R%\" -e \"library('celestial')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=celestial
  license: GPL-3.0-only
  summary: Contains a number of common astronomy conversion routines, particularly the HMS and degrees schemes, which can be fiddly to convert between on mass due to the textural nature of the former. It allows users to coordinate match datasets quickly. It also contains functions for various cosmological calculations.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
