appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AoI0qYq2zNG+qfKJPLMOhVv7b759a4AciIiWXvc1MgJbg1CBmooj7OS/CMQQtm+E8nDoEcb/OUU3wEBJl2k+dq4o785q+V6DSqF5r3QXVEXYcM/J0qDaeyu0a9lMAenQrANBBoDtYfUrAHFR6tAin5l3sfItjlY7c9fMNZNpEFipYJZn4qHNJrn31t2XxxgH4uTjrMAKk3U/3okhQpZ5iiBjiEVc1K4iD0tVZB4UrIXTU+fxsmG1ZEPAiRzagR2TMZjhuLB0S5hsTTKrst8PVoc89akJanNNVTHqLhUoT9XGOmDUsQmRm7TYCJ6K1zZ2lvPwLPToqhUOjLgmZw3+wGeHxG2tqFsg2mbdCF5oRdauxBQZxljL4+aKK81d69/XVYMgX6KVYf0NcyXTgR07IDOCtwDdBQC9HFXBahE+yzX8STMl+5B2ZrnzZJc9Dh+wkvnV1XDuQk4GvZuXSWZpdg6GJ9rAE8RTHY6h928UIDKJRV6IzW62+CVrGh1jq37h496zxWg20yrnWq/avC1dvXlWC/E/g//yMEOT88jMC6P/KeFOvtIetUHiXGuu9bC6B9r145nOKeskL1M/MvsZXbp4U2D5IqbiK5f2fERrh/bWoPduDZUPeMaeV6JPuclV+yjH8lushFpWBHkI0PbdamEwYjodzKGBmzlbGDxWl9g=
